-- ============================================================
-- SEED: Katalog Produk Faktur Penjualan (390 item)
-- Proyek Supabase: iyraamxkrygtzsqkvnqz (UNITOOLS / Universal Tools)
-- Sumber: Productive/Resi-Generator/products.json
-- Cara pakai: Supabase Dashboard > SQL Editor > New query > Paste ini > Run
-- ============================================================

create table if not exists public.faktur_produk (
  sku text primary key,
  name text not null,
  harga numeric(12,0) not null default 0,
  harga_asli numeric(12,0) not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.faktur_produk enable row level security;

-- Anon (browser) boleh SELECT & INSERT/UPDATE agar tool tanpa login bisa memakai DB
drop policy if exists faktur_produk_select on public.faktur_produk;
create policy faktur_produk_select on public.faktur_produk for select to anon using (true);
drop policy if exists faktur_produk_upsert on public.faktur_produk;
create policy faktur_produk_upsert on public.faktur_produk for insert to anon with check (true);
drop policy if exists faktur_produk_update on public.faktur_produk;
create policy faktur_produk_update on public.faktur_produk for update to anon using (true) with check (true);

insert into public.faktur_produk (sku, name) values
('SWP Hitam', 'Waterproof Hitam'),
('SWP Putih', 'Waterproof Putih'),
('SWP Abu', 'Waterproof Abu'),
('SWP Merah', 'Waterproof Merah'),
('SWP Pink', 'Waterproof Pink'),
('SWP Ungu', 'Waterproof Ungu'),
('SWP Biru', 'Waterproof Biru'),
('SWP Hijau', 'Waterproof Hijau'),
('SWP Orange', 'Waterproof Orange'),
('SWP Kuning', 'Waterproof Kuning'),
('SX Hitam-Hitam', 'Xtreme Hitam-Hitam'),
('SX Hitam-Putih', 'Xtreme Hitam-Putih'),
('SX Hitam-Abu', 'Xtreme Hitam-Abu'),
('SX Hitam-Merah', 'Xtreme Hitam-Merah'),
('SX Hitam-Pink', 'Xtreme Hitam-Pink'),
('SX Hitam-Ungu', 'Xtreme Hitam-Ungu'),
('SX Hitam-Biru', 'Xtreme Hitam-Biru'),
('SX Hitam-Hijau', 'Xtreme Hitam-Hijau'),
('SX Hitam-Kuning', 'Xtreme Hitam-Kuning'),
('SX Hitam-Orange', 'Xtreme Hitam-Orange'),
('SX Putih-Hitam', 'Xtreme Putih-Hitam'),
('SX Putih-Putih', 'Xtreme Putih-Putih'),
('SX Putih-Abu', 'Xtreme Putih-Abu'),
('SX Putih-Merah', 'Xtreme Putih-Merah'),
('SX Putih-Pink', 'Xtreme Putih-Pink'),
('SX Putih-Ungu', 'Xtreme Putih-Ungu'),
('SX Putih-Biru', 'Xtreme Putih-Biru'),
('SX Putih-Hijau', 'Xtreme Putih-Hijau'),
('SX Putih-Kuning', 'Xtreme Putih-Kuning'),
('SX Putih-Orange', 'Xtreme Putih-Orange'),
('SX Merah-Hitam', 'Xtreme Merah-Hitam'),
('SX Merah-Putih', 'Xtreme Merah-Putih'),
('SX Merah-Abu', 'Xtreme Merah-Abu'),
('SX Merah-Merah', 'Xtreme Merah-Merah'),
('SX Merah-Pink', 'Xtreme Merah-Pink'),
('SX Merah-Ungu', 'Xtreme Merah-Ungu'),
('SX Merah-Biru', 'Xtreme Merah-Biru'),
('SX Merah-Hijau', 'Xtreme Merah-Hijau'),
('SX Merah-Kuning', 'Xtreme Merah-Kuning'),
('SX Merah-Orange', 'Xtreme Merah-Orange'),
('SX Pink-Hitam', 'Xtreme Pink-Hitam'),
('SX Pink-Putih', 'Xtreme Pink-Putih'),
('SX Pink-Abu', 'Xtreme Pink-Abu'),
('SX Pink-Merah', 'Xtreme Pink-Merah'),
('SX Pink-Pink', 'Xtreme Pink-Pink'),
('SX Pink-Ungu', 'Xtreme Pink-Ungu'),
('SX Pink-Biru', 'Xtreme Pink-Biru'),
('SX Pink-Hijau', 'Xtreme Pink-Hijau'),
('SX Pink-Kuning', 'Xtreme Pink-Kuning'),
('SX Pink-Orange', 'Xtreme Pink-Orange'),
('SX Ungu-Hitam', 'Xtreme Ungu-Hitam'),
('SX Ungu-Putih', 'Xtreme Ungu-Putih'),
('SX Ungu-Abu', 'Xtreme Ungu-Abu'),
('SX Ungu-Merah', 'Xtreme Ungu-Merah'),
('SX Ungu-Pink', 'Xtreme Ungu-Pink'),
('SX Ungu-Ungu', 'Xtreme Ungu-Ungu'),
('SX Ungu-Biru', 'Xtreme Ungu-Biru'),
('SX Ungu-Hijau', 'Xtreme Ungu-Hijau'),
('SX Ungu-Kuning', 'Xtreme Ungu-Kuning'),
('SX Ungu-Orange', 'Xtreme Ungu-Orange'),
('SX Biru-Hitam', 'Xtreme Biru-Hitam'),
('SX Biru-Putih', 'Xtreme Biru-Putih'),
('SX Biru-Abu', 'Xtreme Biru-Abu'),
('SX Biru-Merah', 'Xtreme Biru-Merah'),
('SX Biru-Pink', 'Xtreme Biru-Pink'),
('SX Biru-Ungu', 'Xtreme Biru-Ungu'),
('SX Biru-Biru', 'Xtreme Biru-Biru'),
('SX Biru-Hijau', 'Xtreme Biru-Hijau'),
('SX Biru-Kuning', 'Xtreme Biru-Kuning'),
('SX Biru-Orange', 'Xtreme Biru-Orange'),
('SX Hijau-Hitam', 'Xtreme Hijau-Hitam'),
('SX Hijau-Putih', 'Xtreme Hijau-Putih'),
('SX Hijau-Abu', 'Xtreme Hijau-Abu'),
('SX Hijau-Merah', 'Xtreme Hijau-Merah'),
('SX Hijau-Pink', 'Xtreme Hijau-Pink'),
('SX Hijau-Ungu', 'Xtreme Hijau-Ungu'),
('SX Hijau-Biru', 'Xtreme Hijau-Biru'),
('SX Hijau-Hijau', 'Xtreme Hijau-Hijau'),
('SX Hijau-Kuning', 'Xtreme Hijau-Kuning'),
('SX Hijau-Orange', 'Xtreme Hijau-Orange'),
('SX Kuning-Hitam', 'Xtreme Kuning-Hitam'),
('SX Kuning-Putih', 'Xtreme Kuning-Putih'),
('SX Kuning-Abu', 'Xtreme Kuning-Abu'),
('SX Kuning-Merah', 'Xtreme Kuning-Merah'),
('SX Kuning-Pink', 'Xtreme Kuning-Pink'),
('SX Kuning-Ungu', 'Xtreme Kuning-Ungu'),
('SX Kuning-Biru', 'Xtreme Kuning-Biru'),
('SX Kuning-Hijau', 'Xtreme Kuning-Hijau'),
('SX Kuning-Kuning', 'Xtreme Kuning-Kuning'),
('SX Kuning-Orange', 'Xtreme Kuning-Orange'),
('SX Orange-Hitam', 'Xtreme Orange-Hitam'),
('SX Orange-Putih', 'Xtreme Orange-Putih'),
('SX Orange-Abu', 'Xtreme Orange-Abu'),
('SX Orange-Merah', 'Xtreme Orange-Merah'),
('SX Orange-Pink', 'Xtreme Orange-Pink'),
('SX Orange-Ungu', 'Xtreme Orange-Ungu'),
('SX Orange-Biru', 'Xtreme Orange-Biru'),
('SX Orange-Hijau', 'Xtreme Orange-Hijau'),
('SX Orange-Kuning', 'Xtreme Orange-Kuning'),
('SX Orange-Orange', 'Xtreme Orange-Orange'),
('S Hitam-Hitam', 'Classic Hitam-Hitam'),
('S Hitam-Putih', 'Classic Hitam-Putih'),
('S Hitam-Abu', 'Classic Hitam-Abu'),
('S Hitam-Merah', 'Classic Hitam-Merah'),
('S Hitam-Pink', 'Classic Hitam-Pink'),
('S Hitam-Ungu', 'Classic Hitam-Ungu'),
('S Hitam-Biru', 'Classic Hitam-Biru'),
('S Hitam-Hijau', 'Classic Hitam-Hijau'),
('S Hitam-Kuning', 'Classic Hitam-Kuning'),
('S Hitam-Orange', 'Classic Hitam-Orange'),
('S Putih-Hitam', 'Classic Putih-Hitam'),
('S Putih-Putih', 'Classic Putih-Putih'),
('S Putih-Abu', 'Classic Putih-Abu'),
('S Putih-Merah', 'Classic Putih-Merah'),
('S Putih-Pink', 'Classic Putih-Pink'),
('S Putih-Ungu', 'Classic Putih-Ungu'),
('S Putih-Biru', 'Classic Putih-Biru'),
('S Putih-Hijau', 'Classic Putih-Hijau'),
('S Putih-Kuning', 'Classic Putih-Kuning'),
('S Putih-Orange', 'Classic Putih-Orange'),
('S Merah-Hitam', 'Classic Merah-Hitam'),
('S Merah-Putih', 'Classic Merah-Putih'),
('S Merah-Abu', 'Classic Merah-Abu'),
('S Merah-Merah', 'Classic Merah-Merah'),
('S Merah-Pink', 'Classic Merah-Pink'),
('S Merah-Ungu', 'Classic Merah-Ungu'),
('S Merah-Biru', 'Classic Merah-Biru'),
('S Merah-Hijau', 'Classic Merah-Hijau'),
('S Merah-Kuning', 'Classic Merah-Kuning'),
('S Merah-Orange', 'Classic Merah-Orange'),
('S Pink-Hitam', 'Classic Pink-Hitam'),
('S Pink-Putih', 'Classic Pink-Putih'),
('S Pink-Abu', 'Classic Pink-Abu'),
('S Pink-Merah', 'Classic Pink-Merah'),
('S Pink-Pink', 'Classic Pink-Pink'),
('S Pink-Ungu', 'Classic Pink-Ungu'),
('S Pink-Biru', 'Classic Pink-Biru'),
('S Pink-Hijau', 'Classic Pink-Hijau'),
('S Pink-Kuning', 'Classic Pink-Kuning'),
('S Pink-Orange', 'Classic Pink-Orange'),
('S Ungu-Hitam', 'Classic Ungu-Hitam'),
('S Ungu-Putih', 'Classic Ungu-Putih'),
('S Ungu-Abu', 'Classic Ungu-Abu'),
('S Ungu-Merah', 'Classic Ungu-Merah'),
('S Ungu-Pink', 'Classic Ungu-Pink'),
('S Ungu-Ungu', 'Classic Ungu-Ungu'),
('S Ungu-Biru', 'Classic Ungu-Biru'),
('S Ungu-Hijau', 'Classic Ungu-Hijau'),
('S Ungu-Kuning', 'Classic Ungu-Kuning'),
('S Ungu-Orange', 'Classic Ungu-Orange'),
('S Biru-Hitam', 'Classic Biru-Hitam'),
('S Biru-Putih', 'Classic Biru-Putih'),
('S Biru-Abu', 'Classic Biru-Abu'),
('S Biru-Merah', 'Classic Biru-Merah'),
('S Biru-Pink', 'Classic Biru-Pink'),
('S Biru-Ungu', 'Classic Biru-Ungu'),
('S Biru-Biru', 'Classic Biru-Biru'),
('S Biru-Hijau', 'Classic Biru-Hijau'),
('S Biru-Kuning', 'Classic Biru-Kuning'),
('S Biru-Orange', 'Classic Biru-Orange'),
('S Hijau-Hitam', 'Classic Hijau-Hitam'),
('S Hijau-Putih', 'Classic Hijau-Putih'),
('S Hijau-Abu', 'Classic Hijau-Abu'),
('S Hijau-Merah', 'Classic Hijau-Merah'),
('S Hijau-Pink', 'Classic Hijau-Pink'),
('S Hijau-Ungu', 'Classic Hijau-Ungu'),
('S Hijau-Biru', 'Classic Hijau-Biru'),
('S Hijau-Hijau', 'Classic Hijau-Hijau'),
('S Hijau-Kuning', 'Classic Hijau-Kuning'),
('S Hijau-Orange', 'Classic Hijau-Orange'),
('S Kuning-Hitam', 'Classic Kuning-Hitam'),
('S Kuning-Putih', 'Classic Kuning-Putih'),
('S Kuning-Abu', 'Classic Kuning-Abu'),
('S Kuning-Merah', 'Classic Kuning-Merah'),
('S Kuning-Pink', 'Classic Kuning-Pink'),
('S Kuning-Ungu', 'Classic Kuning-Ungu'),
('S Kuning-Biru', 'Classic Kuning-Biru'),
('S Kuning-Hijau', 'Classic Kuning-Hijau'),
('S Kuning-Kuning', 'Classic Kuning-Kuning'),
('S Kuning-Orange', 'Classic Kuning-Orange'),
('S Orange-Hitam', 'Classic Orange-Hitam'),
('S Orange-Putih', 'Classic Orange-Putih'),
('S Orange-Abu', 'Classic Orange-Abu'),
('S Orange-Merah', 'Classic Orange-Merah'),
('S Orange-Pink', 'Classic Orange-Pink'),
('S Orange-Ungu', 'Classic Orange-Ungu'),
('S Orange-Biru', 'Classic Orange-Biru'),
('S Orange-Hijau', 'Classic Orange-Hijau'),
('S Orange-Kuning', 'Classic Orange-Kuning'),
('S Orange-Orange', 'Classic Orange-Orange'),
('SAG Hitam', 'Aerogrip Hitam'),
('SAG Putih', 'Aerogrip Putih'),
('SAG Abu', 'Aerogrip Abu'),
('SAG Merah', 'Aerogrip Merah'),
('SAG Pink', 'Aerogrip Pink'),
('SAG Ungu', 'Aerogrip Ungu'),
('SAG Biru', 'Aerogrip Biru'),
('SAG Hijau', 'Aerogrip Hijau'),
('SAG Kuning', 'Aerogrip Kuning'),
('SAG Orange', 'Aerogrip Orange'),
('STT Hitam', 'Twotone Embos Hitam'),
('STT Putih', 'Twotone Embos Putih'),
('STT Abu', 'Twotone Embos Abu'),
('STT Merah', 'Twotone Embos Merah'),
('STT Pink', 'Twotone Embos Pink'),
('STT Ungu', 'Twotone Embos Ungu'),
('STT Biru', 'Twotone Embos Biru'),
('STT Hijau', 'Twotone Embos Hijau'),
('STT Kuning', 'Twotone Embos Kuning'),
('STT Orange', 'Twotone Embos Orange'),
('STX Hitam-Hitam', 'Twotone Xtreme Hitam-Hitam'),
('STX Hitam-Putih', 'Twotone Xtreme Hitam-Putih'),
('STX Hitam-Abu', 'Twotone Xtreme Hitam-Abu'),
('STX Hitam-Merah', 'Twotone Xtreme Hitam-Merah'),
('STX Hitam-Pink', 'Twotone Xtreme Hitam-Pink'),
('STX Hitam-Ungu', 'Twotone Xtreme Hitam-Ungu'),
('STX Hitam-Biru', 'Twotone Xtreme Hitam-Biru'),
('STX Hitam-Hijau', 'Twotone Xtreme Hitam-Hijau'),
('STX Hitam-Kuning', 'Twotone Xtreme Hitam-Kuning'),
('STX Hitam-Orange', 'Twotone Xtreme Hitam-Orange'),
('STX Putih-Hitam', 'Twotone Xtreme Putih-Hitam'),
('STX Putih-Putih', 'Twotone Xtreme Putih-Putih'),
('STX Putih-Abu', 'Twotone Xtreme Putih-Abu'),
('STX Putih-Merah', 'Twotone Xtreme Putih-Merah'),
('STX Putih-Pink', 'Twotone Xtreme Putih-Pink'),
('STX Putih-Ungu', 'Twotone Xtreme Putih-Ungu'),
('STX Putih-Biru', 'Twotone Xtreme Putih-Biru'),
('STX Putih-Hijau', 'Twotone Xtreme Putih-Hijau'),
('STX Putih-Kuning', 'Twotone Xtreme Putih-Kuning'),
('STX Putih-Orange', 'Twotone Xtreme Putih-Orange'),
('STX Merah-Hitam', 'Twotone Xtreme Merah-Hitam'),
('STX Merah-Putih', 'Twotone Xtreme Merah-Putih'),
('STX Merah-Abu', 'Twotone Xtreme Merah-Abu'),
('STX Merah-Merah', 'Twotone Xtreme Merah-Merah'),
('STX Merah-Pink', 'Twotone Xtreme Merah-Pink'),
('STX Merah-Ungu', 'Twotone Xtreme Merah-Ungu'),
('STX Merah-Biru', 'Twotone Xtreme Merah-Biru'),
('STX Merah-Hijau', 'Twotone Xtreme Merah-Hijau'),
('STX Merah-Kuning', 'Twotone Xtreme Merah-Kuning'),
('STX Merah-Orange', 'Twotone Xtreme Merah-Orange'),
('STX Pink-Hitam', 'Twotone Xtreme Pink-Hitam'),
('STX Pink-Putih', 'Twotone Xtreme Pink-Putih'),
('STX Pink-Abu', 'Twotone Xtreme Pink-Abu'),
('STX Pink-Merah', 'Twotone Xtreme Pink-Merah'),
('STX Pink-Pink', 'Twotone Xtreme Pink-Pink'),
('STX Pink-Ungu', 'Twotone Xtreme Pink-Ungu'),
('STX Pink-Biru', 'Twotone Xtreme Pink-Biru'),
('STX Pink-Hijau', 'Twotone Xtreme Pink-Hijau'),
('STX Pink-Kuning', 'Twotone Xtreme Pink-Kuning'),
('STX Pink-Orange', 'Twotone Xtreme Pink-Orange'),
('STX Ungu-Hitam', 'Twotone Xtreme Ungu-Hitam'),
('STX Ungu-Putih', 'Twotone Xtreme Ungu-Putih'),
('STX Ungu-Abu', 'Twotone Xtreme Ungu-Abu'),
('STX Ungu-Merah', 'Twotone Xtreme Ungu-Merah'),
('STX Ungu-Pink', 'Twotone Xtreme Ungu-Pink'),
('STX Ungu-Ungu', 'Twotone Xtreme Ungu-Ungu'),
('STX Ungu-Biru', 'Twotone Xtreme Ungu-Biru'),
('STX Ungu-Hijau', 'Twotone Xtreme Ungu-Hijau'),
('STX Ungu-Kuning', 'Twotone Xtreme Ungu-Kuning'),
('STX Ungu-Orange', 'Twotone Xtreme Ungu-Orange'),
('STX Biru-Hitam', 'Twotone Xtreme Biru-Hitam'),
('STX Biru-Putih', 'Twotone Xtreme Biru-Putih'),
('STX Biru-Abu', 'Twotone Xtreme Biru-Abu'),
('STX Biru-Merah', 'Twotone Xtreme Biru-Merah'),
('STX Biru-Pink', 'Twotone Xtreme Biru-Pink'),
('STX Biru-Ungu', 'Twotone Xtreme Biru-Ungu'),
('STX Biru-Biru', 'Twotone Xtreme Biru-Biru'),
('STX Biru-Hijau', 'Twotone Xtreme Biru-Hijau'),
('STX Biru-Kuning', 'Twotone Xtreme Biru-Kuning'),
('STX Biru-Orange', 'Twotone Xtreme Biru-Orange'),
('STX Hijau-Hitam', 'Twotone Xtreme Hijau-Hitam'),
('STX Hijau-Putih', 'Twotone Xtreme Hijau-Putih'),
('STX Hijau-Abu', 'Twotone Xtreme Hijau-Abu'),
('STX Hijau-Merah', 'Twotone Xtreme Hijau-Merah'),
('STX Hijau-Pink', 'Twotone Xtreme Hijau-Pink'),
('STX Hijau-Ungu', 'Twotone Xtreme Hijau-Ungu'),
('STX Hijau-Biru', 'Twotone Xtreme Hijau-Biru'),
('STX Hijau-Hijau', 'Twotone Xtreme Hijau-Hijau'),
('STX Hijau-Kuning', 'Twotone Xtreme Hijau-Kuning'),
('STX Hijau-Orange', 'Twotone Xtreme Hijau-Orange'),
('STX Kuning-Hitam', 'Twotone Xtreme Kuning-Hitam'),
('STX Kuning-Putih', 'Twotone Xtreme Kuning-Putih'),
('STX Kuning-Abu', 'Twotone Xtreme Kuning-Abu'),
('STX Kuning-Merah', 'Twotone Xtreme Kuning-Merah'),
('STX Kuning-Pink', 'Twotone Xtreme Kuning-Pink'),
('STX Kuning-Ungu', 'Twotone Xtreme Kuning-Ungu'),
('STX Kuning-Biru', 'Twotone Xtreme Kuning-Biru'),
('STX Kuning-Hijau', 'Twotone Xtreme Kuning-Hijau'),
('STX Kuning-Kuning', 'Twotone Xtreme Kuning-Kuning'),
('STX Kuning-Orange', 'Twotone Xtreme Kuning-Orange'),
('STX Orange-Hitam', 'Twotone Xtreme Orange-Hitam'),
('STX Orange-Putih', 'Twotone Xtreme Orange-Putih'),
('STX Orange-Abu', 'Twotone Xtreme Orange-Abu'),
('STX Orange-Merah', 'Twotone Xtreme Orange-Merah'),
('STX Orange-Pink', 'Twotone Xtreme Orange-Pink'),
('STX Orange-Ungu', 'Twotone Xtreme Orange-Ungu'),
('STX Orange-Biru', 'Twotone Xtreme Orange-Biru'),
('STX Orange-Hijau', 'Twotone Xtreme Orange-Hijau'),
('STX Orange-Kuning', 'Twotone Xtreme Orange-Kuning'),
('STX Orange-Orange', 'Twotone Xtreme Orange-Orange'),
('STC Hitam-Hitam', 'Twotone Classic Hitam-Hitam'),
('STC Hitam-Putih', 'Twotone Classic Hitam-Putih'),
('STC Hitam-Abu', 'Twotone Classic Hitam-Abu'),
('STC Hitam-Merah', 'Twotone Classic Hitam-Merah'),
('STC Hitam-Pink', 'Twotone Classic Hitam-Pink'),
('STC Hitam-Ungu', 'Twotone Classic Hitam-Ungu'),
('STC Hitam-Biru', 'Twotone Classic Hitam-Biru'),
('STC Hitam-Hijau', 'Twotone Classic Hitam-Hijau'),
('STC Hitam-Kuning', 'Twotone Classic Hitam-Kuning'),
('STC Hitam-Orange', 'Twotone Classic Hitam-Orange'),
('STC Putih-Hitam', 'Twotone Classic Putih-Hitam'),
('STC Putih-Putih', 'Twotone Classic Putih-Putih'),
('STC Putih-Abu', 'Twotone Classic Putih-Abu'),
('STC Putih-Merah', 'Twotone Classic Putih-Merah'),
('STC Putih-Pink', 'Twotone Classic Putih-Pink'),
('STC Putih-Ungu', 'Twotone Classic Putih-Ungu'),
('STC Putih-Biru', 'Twotone Classic Putih-Biru'),
('STC Putih-Hijau', 'Twotone Classic Putih-Hijau'),
('STC Putih-Kuning', 'Twotone Classic Putih-Kuning'),
('STC Putih-Orange', 'Twotone Classic Putih-Orange'),
('STC Merah-Hitam', 'Twotone Classic Merah-Hitam'),
('STC Merah-Putih', 'Twotone Classic Merah-Putih'),
('STC Merah-Abu', 'Twotone Classic Merah-Abu'),
('STC Merah-Merah', 'Twotone Classic Merah-Merah'),
('STC Merah-Pink', 'Twotone Classic Merah-Pink'),
('STC Merah-Ungu', 'Twotone Classic Merah-Ungu'),
('STC Merah-Biru', 'Twotone Classic Merah-Biru'),
('STC Merah-Hijau', 'Twotone Classic Merah-Hijau'),
('STC Merah-Kuning', 'Twotone Classic Merah-Kuning'),
('STC Merah-Orange', 'Twotone Classic Merah-Orange'),
('STC Pink-Hitam', 'Twotone Classic Pink-Hitam'),
('STC Pink-Putih', 'Twotone Classic Pink-Putih'),
('STC Pink-Abu', 'Twotone Classic Pink-Abu'),
('STC Pink-Merah', 'Twotone Classic Pink-Merah'),
('STC Pink-Pink', 'Twotone Classic Pink-Pink'),
('STC Pink-Ungu', 'Twotone Classic Pink-Ungu'),
('STC Pink-Biru', 'Twotone Classic Pink-Biru'),
('STC Pink-Hijau', 'Twotone Classic Pink-Hijau'),
('STC Pink-Kuning', 'Twotone Classic Pink-Kuning'),
('STC Pink-Orange', 'Twotone Classic Pink-Orange'),
('STC Ungu-Hitam', 'Twotone Classic Ungu-Hitam'),
('STC Ungu-Putih', 'Twotone Classic Ungu-Putih'),
('STC Ungu-Abu', 'Twotone Classic Ungu-Abu'),
('STC Ungu-Merah', 'Twotone Classic Ungu-Merah'),
('STC Ungu-Pink', 'Twotone Classic Ungu-Pink'),
('STC Ungu-Ungu', 'Twotone Classic Ungu-Ungu'),
('STC Ungu-Biru', 'Twotone Classic Ungu-Biru'),
('STC Ungu-Hijau', 'Twotone Classic Ungu-Hijau'),
('STC Ungu-Kuning', 'Twotone Classic Ungu-Kuning'),
('STC Ungu-Orange', 'Twotone Classic Ungu-Orange'),
('STC Biru-Hitam', 'Twotone Classic Biru-Hitam'),
('STC Biru-Putih', 'Twotone Classic Biru-Putih'),
('STC Biru-Abu', 'Twotone Classic Biru-Abu'),
('STC Biru-Merah', 'Twotone Classic Biru-Merah'),
('STC Biru-Pink', 'Twotone Classic Biru-Pink'),
('STC Biru-Ungu', 'Twotone Classic Biru-Ungu'),
('STC Biru-Biru', 'Twotone Classic Biru-Biru'),
('STC Biru-Hijau', 'Twotone Classic Biru-Hijau'),
('STC Biru-Kuning', 'Twotone Classic Biru-Kuning'),
('STC Biru-Orange', 'Twotone Classic Biru-Orange'),
('STC Hijau-Hitam', 'Twotone Classic Hijau-Hitam'),
('STC Hijau-Putih', 'Twotone Classic Hijau-Putih'),
('STC Hijau-Abu', 'Twotone Classic Hijau-Abu'),
('STC Hijau-Merah', 'Twotone Classic Hijau-Merah'),
('STC Hijau-Pink', 'Twotone Classic Hijau-Pink'),
('STC Hijau-Ungu', 'Twotone Classic Hijau-Ungu'),
('STC Hijau-Biru', 'Twotone Classic Hijau-Biru'),
('STC Hijau-Hijau', 'Twotone Classic Hijau-Hijau'),
('STC Hijau-Kuning', 'Twotone Classic Hijau-Kuning'),
('STC Hijau-Orange', 'Twotone Classic Hijau-Orange'),
('STC Kuning-Hitam', 'Twotone Classic Kuning-Hitam'),
('STC Kuning-Putih', 'Twotone Classic Kuning-Putih'),
('STC Kuning-Abu', 'Twotone Classic Kuning-Abu'),
('STC Kuning-Merah', 'Twotone Classic Kuning-Merah'),
('STC Kuning-Pink', 'Twotone Classic Kuning-Pink'),
('STC Kuning-Ungu', 'Twotone Classic Kuning-Ungu'),
('STC Kuning-Biru', 'Twotone Classic Kuning-Biru'),
('STC Kuning-Hijau', 'Twotone Classic Kuning-Hijau'),
('STC Kuning-Kuning', 'Twotone Classic Kuning-Kuning'),
('STC Kuning-Orange', 'Twotone Classic Kuning-Orange'),
('STC Orange-Hitam', 'Twotone Classic Orange-Hitam'),
('STC Orange-Putih', 'Twotone Classic Orange-Putih'),
('STC Orange-Abu', 'Twotone Classic Orange-Abu'),
('STC Orange-Merah', 'Twotone Classic Orange-Merah'),
('STC Orange-Pink', 'Twotone Classic Orange-Pink'),
('STC Orange-Ungu', 'Twotone Classic Orange-Ungu'),
('STC Orange-Biru', 'Twotone Classic Orange-Biru'),
('STC Orange-Hijau', 'Twotone Classic Orange-Hijau'),
('STC Orange-Kuning', 'Twotone Classic Orange-Kuning'),
('STC Orange-Orange', 'Twotone Classic Orange-Orange')

on conflict (sku) do update set name = excluded.name, updated_at = now();