/* utils */
(function(){'use strict';
var U={};
U.$id=function(id){return document.getElementById(id)};
U.debounce=function(fn,ms){var t=null;return function(){var c=this,a=arguments;if(t)clearTimeout(t);t=setTimeout(function(){fn.apply(c,a);t=null},ms)}};
U.esc=function(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')};
U.sanitize=function(s){return String(s).replace(/<[^>]*>/g,'').replace(/[<>\"'`]/g,'').trim()};
U.copyToClipboard=function(t){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(t).then(function(){return true});return new Promise(function(r){var a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{r(document.execCommand('copy'))}catch(e){r(false)}document.body.removeChild(a)})};
U.relTime=function(d){if(d===0)return'Hari ini';if(d===1)return'Kemarin';if(d<=7)return d+' hari lalu';if(d<=30)return Math.floor(d/7)+' minggu lalu';if(d<=365)return Math.floor(d/30)+' bulan lalu';return Math.floor(d/365)+' tahun lalu'};
U.favIcon=function(url){try{return'https://www.google.com/s2/favicons?domain='+new URL(url).hostname+'&sz=64'}catch(e){return''}};
U.svcIcon=function(url){try{var u=new URL(url);if(u.hostname==='drive.google.com')return'https://ssl.gstatic.com/images/branding/product/2x/drive_2020q4_32dp.png';if(u.hostname==='docs.google.com'){if(u.pathname.includes('spreadsheets'))return'https://ssl.gstatic.com/images/branding/product/2x/sheets_2020q4_32dp.png';if(u.pathname.includes('presentation'))return'https://ssl.gstatic.com/images/branding/product/2x/slides_2020q4_32dp.png';if(u.pathname.includes('forms'))return'https://ssl.gstatic.com/images/branding/product/2x/forms_2020q4_32dp.png';return'https://ssl.gstatic.com/images/branding/product/2x/docs_2020q4_32dp.png'}return null}catch(e){return null}};
U.onError=function(imgEl,url){return function(){var f=U.favIcon(url);if(f){imgEl.src=f;imgEl.onerror=function(){imgEl.parentElement.innerHTML='🔗'}}else imgEl.parentElement.innerHTML='🔗'}};
window.LATCH=window.LATCH||{};window.LATCH.utils=U;
})();

/* state */
(function(){'use strict';
function State(initial){var s=JSON.parse(JSON.stringify(initial||{}));var ls={};function g(k){return k?s[k]:s}function S(k,v){if(typeof k==='object'){Object.keys(k).forEach(function(x){s[x]=k[x]});Object.keys(k).forEach(function(x){e(x,s[x])});e('*',s);return}s[k]=v;e(k,v);e('*',s)}function o(e,f){if(!ls[e])ls[e]=[];ls[e].push(f);return function(){return ls[e]=ls[e].filter(function(g){return g!==f})}}function O(e,f){if(!ls[e])return;ls[e]=ls[e].filter(function(g){return g!==f})}function e(event,data){if(!ls[event])return;ls[event].forEach(function(f){try{f(data)}catch(x){console.error('[State]',x)}})}function D(){Object.keys(ls).forEach(function(k){delete ls[k]})}return{get:g,set:S,on:o,off:O,emit:e,destroy:D}}
var store=State({mode:'view',isAdmin:false,cats:[],links:[],viewCats:[],search:'',tab:'all',delId:null,loading:false,toast:null});
window.LATCH=window.LATCH||{};window.LATCH.state=store;
})();

/* storage */
(function(){'use strict';
var S={};
var st=typeof PropertiesService!=='undefined'?{get:function(k){return PropertiesService.getScriptProperties().getProperty(k)},set:function(k,v){PropertiesService.getScriptProperties().setProperty(k,v)},remove:function(k){PropertiesService.getScriptProperties().deleteProperty(k)}}:{get:function(k){try{return localStorage.getItem(k)}catch(e){return null}},set:function(k,v){try{localStorage.setItem(k,v)}catch(e){}},remove:function(k){try{localStorage.removeItem(k)}catch(e){}}};
S.get=function(k,d){try{var r=st.get(k);if(r===null||r===undefined)return d;try{return JSON.parse(r)}catch(e){return r}}catch(e){return d}};
S.set=function(k,v){try{st.set(k,typeof v==='string'?v:JSON.stringify(v))}catch(e){}};
S.remove=function(k){try{st.remove(k)}catch(e){}};
window.LATCH=window.LATCH||{};window.LATCH.storage=S;
})();

/* db */
(function(){'use strict';
var U=window.LATCH.utils;
var cache={};
var GAS_URL='https://script.google.com/macros/s/AKfycbxqvMkROtZRuTnaRVxTM_pYAIJepZWkebPvSOyP5BQS99JxLlOXnHObJvKesAVVg0V1/exec';
function invalidate(){cache={}}
function cached(k,t,f){return new Promise(function(r,e){var n=Date.now();if(cache[k]&&(n-cache[k].time<t)){r(cache[k].data);return}f().then(function(d){cache[k]={data:d,time:n};r(d)}).catch(e)})}
function gasFetch(action,payload){var url=GAS_URL+'?action='+encodeURIComponent(action);var opts={method:payload?'POST':'GET',headers:{},redirect:'follow'};if(payload){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(payload)}var to=false;var tm=setTimeout(function(){to=true},12000);return fetch(url,opts).then(function(r){if(to)return;clearTimeout(tm);if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(function(t){if(to)throw new Error('Timeout');return JSON.parse(t)})}
var DB={getData:function(f){if(f)invalidate();return cached('allData',5000,function(){return gasFetch('getData').then(function(d){if(d&&d.categories){d.categories.sort(function(a,b){return(a.sort||0)-(b.sort||0)})}return d})})},verifyPin:function(p){return gasFetch('verifyPin',{pin:p})},addRow:function(d){return gasFetch('addRow',d).then(function(r){if(r&&r.success)invalidate();return r})},saveRow:function(id,d){return gasFetch('saveRow',Object.assign({id:id},d)).then(function(r){if(r&&r.success)invalidate();return r})},deleteRow:function(id){return gasFetch('deleteRow',{id:id}).then(function(r){if(r&&r.success)invalidate();return r})},deleteMany:function(ids){return gasFetch('deleteMany',{ids:ids}).then(function(r){if(r&&r.success)invalidate();return r})},addCategory:function(n){return gasFetch('addCategory',{name:n}).then(function(r){if(r&&r.success)invalidate();return r})},deleteCategory:function(id){return gasFetch('deleteCategory',{id:id}).then(function(r){if(r&&r.success)invalidate();return r})},reorderLinks:function(cId,oIds){return gasFetch('reorderLinks',{catId:cId,orderedIds:oIds}).then(function(r){if(r&&r.success)invalidate();return r})},invalidate:invalidate};
window.LATCH=window.LATCH||{};window.LATCH.db=DB;
})();

/* layout */
(function(){'use strict';
var LO={};var loaded={};
function fromInline(name){var e=document.getElementById('fragment-'+name);if(!e)return null;var h=e.innerHTML;e.remove();return h}
LO.loadFragment=function(name){return new Promise(function(r,e){if(loaded[name]){r(loaded[name]);return}var f=fromInline(name);if(f){loaded[name]=f;r(f);return}fetch('views/'+name+'.html').then(function(x){if(!x.ok)throw new Error('Failed');return x.text()}).then(function(h){loaded[name]=h;r(h)}).catch(function(err){console.error('[Layout]',name,err);e(err)})})};
LO.loadAll=function(names){return Promise.all(names.map(function(n){return LO.loadFragment(n)}))};
LO.render=function(){var app=document.getElementById('app');if(!app)return Promise.reject(new Error('#app not found'));app.innerHTML='';return LO.loadAll(['public','admin','modals','footer']).then(function(fs){app.innerHTML=fs.join('')})};
window.LATCH=window.LATCH||{};window.LATCH.layout=LO;
})();

/* components */
(function(){'use strict';
var state=window.LATCH.state;var U=window.LATCH.utils;var C={};
C.toast=function(m,t){t=t||'info';var e=document.querySelector('.latch-toast');if(e)e.remove();var el=document.createElement('div');el.className='latch-toast latch-toast-'+t;el.textContent=m;document.body.appendChild(el);requestAnimationFrame(function(){el.classList.add('latch-toast-visible')});setTimeout(function(){el.classList.remove('latch-toast-visible');setTimeout(function(){el.remove()},300)},3000)};
C.toastUndo=function(m,onUndo){var el=document.createElement('div');el.className='latch-toast latch-toast-info latch-toast-undo';el.innerHTML='<span>'+m+'</span><button class="toast-undo-btn">Undo</button>';document.body.appendChild(el);requestAnimationFrame(function(){el.classList.add('latch-toast-visible')});var t=setTimeout(function(){el.classList.remove('latch-toast-visible');setTimeout(function(){el.remove()},300)},5000);el.querySelector('.toast-undo-btn').addEventListener('click',function(){clearTimeout(t);if(onUndo)onUndo();el.classList.remove('latch-toast-visible');setTimeout(function(){el.remove()},300)})};
C.showLoading=function(){var el=U.$id('loadingOverlay');if(!el)return;el.innerHTML='<div class="skeleton-grid">'+Array(6).fill('<div class="skeleton-card"><div class="skeleton-row"><div class="skeleton-icon"></div><div class="skeleton-lines"><div class="skeleton-line w-60"></div><div class="skeleton-line w-30"></div></div></div></div>').join('')+'</div>';el.style.display='flex'};
C.hideLoading=function(){var el=U.$id('loadingOverlay');if(el)el.style.display='none'};
C.shakeElement=function(el){if(!el)return;el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake');setTimeout(function(){el.classList.remove('shake')},400)};
C.showModal=function(id){var el=U.$id(id);if(el){el.style.display='flex';el.classList.add('modal-open');C.trapFocus(el)}};
C.hideModal=function(id){var el=U.$id(id);if(el){el.style.display='none';el.classList.remove('modal-open');var e=new Event('modal-closed');el.dispatchEvent(e)}};
C.trapFocus=function(c){var f=c.querySelectorAll('button,input,select,textarea,[tabindex]:not([tabindex="-1"])');if(!f.length)return;var first=f[0],last=f[f.length-1];if(first)first.focus();function h(e){if(e.key!=='Tab')return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}c.addEventListener('keydown',h);c.addEventListener('modal-closed',function(){c.removeEventListener('keydown',h)})};
C.skeletonHTML=function(c){c=c||6;return'<div class="skeleton-grid">'+Array(c).fill('<div class="skeleton-card"><div class="skeleton-row"><div class="skeleton-icon"></div><div class="skeleton-lines"><div class="skeleton-line w-60"></div><div class="skeleton-line w-30"></div></div></div></div>').join('')+'</div>'};
C.renderError=function(m){return'<div class="error-state"><svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" stroke-width="1.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg><p>'+U.esc(m)+'</p></div>'};
window.LATCH=window.LATCH||{};window.LATCH.components=C;
})();

/* view */
(function(){'use strict';
var state=window.LATCH.state;var db=window.LATCH.db;var C=window.LATCH.components;var U=window.LATCH.utils;var $=U.$id;var V={};
var flt={};function ic(){flt={}}
function gl(){var k=state.get('tab')+'::'+state.get('search');if(flt[k])return flt[k];var v=state.get('viewCats'),c=v.find(function(x){return x.id===state.get('tab')});if(!c)return[];var l=c.links,q=state.get('search').toLowerCase().trim();if(q)l=l.filter(function(x){return x.title.toLowerCase().includes(q)||x.url.toLowerCase().includes(q)});flt[k]=l;return l}
V.renderTabs=function(){var el=$('tabsContainer'),w=$('tabsWrapper');if(!el)return;el.setAttribute('role','tablist');if(w)w.scrollLeft=0;var cur=state.get('tab');el.innerHTML=state.get('viewCats').map(function(c){return'<button class="tab-chip '+(c.id===cur?'active':'')+'" data-id="'+c.id+'" role="tab" aria-selected="'+(c.id===cur?'true':'false')+'"><i data-feather="'+c.feather+'"></i><span>'+U.esc(c.name)+'</span><span class="tab-count">'+c.links.length+'</span></button>'}).join('');el.querySelectorAll('.tab-chip').forEach(function(b){b.addEventListener('click',function(){V.switchTab(this.dataset.id)})});if(typeof feather!=='undefined')feather.replace()};
V.switchTab=function(id){var pt=state.get('tab'),sc=state.get('searchCache')||{},inp=$('searchInput');if(inp&&pt){sc[pt]=inp.value}var rs=sc[id]||'';state.set({tab:id,search:rs});if(inp)inp.value=rs;state.set('searchCache',sc);ic();V.renderTabs();var g=$('linksGrid');if(g){if(g._scrollObs)g._scrollObs.disconnect();g._scrollObs=null;g._allData=null;g._batchCount=0}V.renderLinks();if(inp)inp.focus()};
function hl(t,q){if(!q)return U.esc(t);var r=new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi');return U.esc(t).replace(r,'<span class="search-highlight">$1</span>')}
var BS=24;
function rl(l,i,q,ic,cb,ht){return'<div class="link-card-wrap" style="animation-delay:'+i%12*50+'ms"><a href="'+U.esc(l.url)+'" target="_blank" rel="noopener noreferrer" class="link-card-row'+(l.badge==='hot'?' link-hot':'')+'" data-url="'+U.esc(l.url)+'"><div class="link-icon-row"><img src="'+ic+'" alt="" loading="lazy" decoding="async" onerror="'+cb+'"></div><div class="link-content-row"><span class="link-title-row" title="'+U.esc(l.title)+'">'+ht+'</span><span class="link-meta-row">'+U.relTime(l.updated)+'</span></div></a><button class="link-copy-btn" data-url="'+U.esc(l.url)+'" title="Salin link">📋</button></div>'}
function pd(l,q){var ic=U.svcIcon(l.url)||U.favIcon(l.url),cb=U.svcIcon(l.url)?'var f=\''+U.favIcon(l.url)+'\';if(f){this.src=f;this.onerror=function(){this.parentElement.innerHTML=\'🔗\'}}else{this.parentElement.innerHTML=\'🔗\'}':'this.parentElement.innerHTML=\'🔗\'';return{ic:ic,cb:cb,ht:hl(l.title,q)}}
V.renderLinks=function(){var g=$('linksGrid'),c=$('gridCounter'),nr=$('noResults');if(!g)return;var ls=gl(),q=state.get('search');if(!ls.length){g.innerHTML='';if(c)c.textContent='';if(nr){var cat=state.get('viewCats').find(function(x){return x.id===state.get('tab')});if(q){nr.querySelector('.no-results-title').textContent='Tidak ada link ditemukan';nr.querySelector('.no-results-hint').textContent='Coba ubah kata kunci pencarian'}else if(cat&&cat.name!=='Semua'){nr.querySelector('.no-results-title').textContent='Kategori "'+cat.name+'" kosong';nr.querySelector('.no-results-hint').textContent='Belum ada link di kategori ini'}else{nr.querySelector('.no-results-title').textContent='Belum ada link';nr.querySelector('.no-results-hint').textContent='Tambahkan link pertama Anda'}nr.style.display='flex'}g._batchCount=0;return}if(nr)nr.style.display='none';var sl=ls.slice().sort(function(a,b){return(typeof a.sort==='number'?a.sort:0)-(typeof b.sort==='number'?b.sort:0)});g._allData=sl;g._batchCount=0;g.innerHTML='';V.renderBatch(g);V.setupInfiniteScroll(g);V.updateCounter(g)};
V.updateCounter=function(g){var c=$('gridCounter');if(!c)return;var d=g._allData||[],l=Math.min(g._batchCount*BS,d.length),q=state.get('search'),cat=state.get('viewCats').find(function(x){return x.id===state.get('tab')}),t=cat?cat.links.length:0,ta=state.get('links')?state.get('links').length:0,cc=state.get('viewCats')?state.get('viewCats').length-1:0,lb=cat?cat.name:'Semua';c.textContent=q?'Menampilkan '+d.length+' dari '+t+' link · "'+lb+'"':'Menampilkan '+l+'/'+d.length+' link di '+lb+' · '+ta+' total · '+cc+' folder'};
V.renderBatch=function(g){var d=g._allData||[],s=g._batchCount*BS,e=Math.min(s+BS,d.length);if(s>=d.length)return;var lm=g.querySelector('.load-more');if(lm)lm.remove();var q=state.get('search'),html='',frag=document.createDocumentFragment(),tmp=document.createElement('div');for(var i=s;i<e;i++){var l=d[i],p=pd(l,q);html+=rl(l,i,q,p.ic,p.cb,p.ht)}tmp.innerHTML=html;while(tmp.firstChild)frag.appendChild(tmp.firstChild);g.appendChild(frag);g._batchCount++;V.updateCounter(g);g.querySelectorAll('.link-copy-btn').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();U.copyToClipboard(this.dataset.url).then(function(ok){if(ok)C.toast('Link disalin','success');else C.toast('Gagal menyalin link','error')})})});if(e<d.length){if(!lm){lm=document.createElement('div');lm.className='load-more'}lm.textContent='Muat lebih banyak...';lm.onclick=function(){V.renderBatch(g)};g.appendChild(lm)}else{var done=document.createElement('div');done.className='load-all-done';done.textContent='— Semua ditampilkan —';g.appendChild(done)}};
V.setupInfiniteScroll=function(g){if(g._scrollObs)g._scrollObs.disconnect();var s=document.createElement('div');s.className='scroll-sentinel';g.appendChild(s);g._scrollObs=new IntersectionObserver(function(e){if(e[0].isIntersecting){var b=g._batchCount;V.renderBatch(g);var d=g._allData||[];if(g._batchCount*BS>=d.length){g._scrollObs.disconnect();var x=g.querySelector('.scroll-sentinel');if(x)x.remove();if(b===g._batchCount&&d.length>0){var done=document.createElement('div');done.className='load-all-done';done.textContent='— Semua ditampilkan —';g.appendChild(done)}}}},{rootMargin:'200px'});g._scrollObs.observe(s)};
V.render=function(){V.renderTabs();V.renderLinks()};
V.onSearch=function(v){state.set('search',v);ic();V.renderLinks()};
V.startClock=function(){var e=$('atmClock');if(!e||e.dataset.clockStarted)return;e.dataset.clockStarted='1';function u(){var d=new Date(),days=['Min','Sen','Sel','Rab','Kam','Jum','Sab'],months=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];e.textContent=days[d.getDay()]+', '+d.getDate()+' '+months[d.getMonth()]+' '+d.getFullYear()+' · '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}u();setInterval(u,30000)};
V.initBackToTop=function(){var b=$('backToTop');if(!b)return;window.addEventListener('scroll',function(){b.classList.toggle('visible',window.scrollY>300)},{passive:true});b.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'})})};
V.initSwipe=function(){var g=$('linksGrid');if(!g)return;var sx=0,sy=0;g.addEventListener('touchstart',function(e){sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});g.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)<50||Math.abs(dy)>Math.abs(dx)*1.5)return;var vc=state.get('viewCats'),cur=state.get('tab'),idx=vc.findIndex(function(c){return c.id===cur});if(dx<0&&idx<vc.length-1)V.switchTab(vc[idx+1].id);else if(dx>0&&idx>0)V.switchTab(vc[idx-1].id)},{passive:true})};
V.init=function(){V.render();V.startClock();V.initBackToTop();V.initSwipe()};
window.LATCH=window.LATCH||{};window.LATCH.view=V;
})();

/* dashboard */
(function(){'use strict';
var state=window.LATCH.state;var db=window.LATCH.db;var C=window.LATCH.components;var U=window.LATCH.utils;var $=U.$id;var D={};var sel={};var sm=false;
function cn(id){var c=state.get('cats').find(function(x){return x.id===id});return c?c.name:''}
function ci(name){var c=state.get('cats').find(function(x){return x.name===name});return c?c.id:''}
D.render=function(){D.renderTable();D.renderNav();D.renderCount();D.updateDrawerCatList()};
D.renderTable=function(){var el=$('dashboardTable');if(!el)return;var cats=state.get('cats'),
links=state.get('links'),q=($('dashSearchInput')||{}).value||'',html='',total=0;
cats.forEach(function(cat){var cl=links.filter(function(l){return l.categoryId===cat.id});cl.sort(function(a,b){return(typeof a.sort==='number'?a.sort:0)-(typeof b.sort==='number'?b.sort:0)});if(!cl.length)return;if(q){cl=cl.filter(function(l){return l.title.toLowerCase().indexOf(q.toLowerCase())!==-1||l.url.toLowerCase().indexOf(q.toLowerCase())!==-1});if(!cl.length)return}total+=cl.length;html+='<div class="dash-group" id="dash-group-'+cat.id+'" data-cat="'+cat.id+'"><div class="dash-group-header"><i data-feather="'+cat.feather+'"></i><span>'+U.esc(cat.name)+'</span><span class="tab-count">'+cl.length+'</span></div>';cl.forEach(function(l){var cnn=cn(l.categoryId),chk=sel[l.id]?'checked':'',co=state.get('cats').map(function(c){return'<option value="'+U.esc(c.name)+'" '+(c.name===cnn?'selected':'')+'>'+U.esc(c.name)+'</option>'}).join('');html+='<div class="dash-row'+(sel[l.id]?' selected':'')+'" data-id="'+l.id+'" draggable="true"><div class="dash-field dash-grip" data-a="grip" title="Seret">⠿</div><div class="dash-field dash-title" style="display:flex;align-items:center;gap:4px"><input type="checkbox" class="dash-checkbox" data-a="check" '+chk+'><input type="text" value="'+U.esc(l.title)+'" data-f="title"></div><div class="dash-field dash-url"><input type="text" value="'+U.esc(l.url)+'" data-f="url"></div><div class="dash-field dash-cat"><div class="dash-select-wrap"><select data-f="cat">'+co+'</select><svg class="dash-select-arrow" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"></polyline></svg></div></div><div class="dash-field dash-time"><span>'+U.relTime(l.updated)+'</span></div><div class="dash-field dash-act"><button class="dash-btn dash-btn-danger" data-a="del" title="Hapus">🗑</button><button class="dash-btn dash-btn-save" data-a="save" title="Simpan" style="display:none">💾</button><button class="dash-btn" data-a="copy" title="Salin link">📋</button></div></div>'});html+='</div>'});el.innerHTML=html;
links.forEach(function(l){l._orig={title:l.title,url:l.url,cat:cn(l.categoryId)}});
var dsi=null,dsg=null;
el.querySelectorAll('.dash-row').forEach(function(row){row.querySelectorAll('input[data-f]').forEach(function(inp){inp.addEventListener('input',function(){rw(row)})});row.querySelectorAll('select[data-f]').forEach(function(sel){sel.addEventListener('change',function(){rw(row)})});var db=row.querySelector('[data-a="del"]'),sb=row.querySelector('[data-a="save"]'),cb2=row.querySelector('[data-a="copy"]'),ch=row.querySelector('[data-a="check"]');if(db)db.addEventListener('click',function(){dc(row.dataset.id)});if(sb)sb.addEventListener('click',function(){sc(row.dataset.id)});if(cb2)cb2.addEventListener('click',function(){cl2(row.dataset.id)});if(ch)ch.addEventListener('change',function(){ts(row.dataset.id,this.checked)});
row.addEventListener('dragstart',function(e){dsi=this.dataset.id;dsg=this.closest('.dash-group');this.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',this.dataset.id)});
row.addEventListener('dragend',function(){this.classList.remove('dragging');el.querySelectorAll('.dash-row.drag-over').forEach(function(r){r.classList.remove('drag-over')});dsi=null;dsg=null});
row.addEventListener('dragover',function(e){e.preventDefault();e.dataTransfer.dropEffect='move'});
row.addEventListener('dragenter',function(e){e.preventDefault();if(this.dataset.id!==dsi)this.classList.add('drag-over')});
row.addEventListener('dragleave',function(){this.classList.remove('drag-over')});
row.addEventListener('drop',function(e){e.preventDefault();this.classList.remove('drag-over');var tId=this.dataset.id;if(!dsi||dsi===tId)return;var sg=dsg,tg=this.closest('.dash-group');if(sg&&tg&&sg.dataset.cat!==tg.dataset.cat)return;var g=tg||sg;if(!g)return;var cId=g.dataset.cat,rows=g.querySelectorAll('.dash-row'),oIds=[];rows.forEach(function(r){if(r.dataset.id===dsi)return;if(r.dataset.id===tId)oIds.push(dsi);oIds.push(r.dataset.id)});if(oIds.indexOf(dsi)===-1)oIds.push(dsi);db.reorderLinks(cId,oIds).then(function(r){if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});D.renderTable()})}})});if(typeof feather!=='undefined')feather.replace();D.updateCatList()});
function cl2(id){var l=state.get('links').find(function(x){return x.id===id});if(!l)return;U.copyToClipboard(l.url).then(function(ok){C.toast(ok?'Link disalin: '+l.title:'Gagal','success')})}
function ts(id,c){if(c)sel[id]=true;else delete sel[id];var r=$('dashboardTable').querySelector('[data-id="'+id+'"]');if(r){r.classList.toggle('selected',!!sel[id]);r.querySelector('[data-a="check"]').checked=!!sel[id]}ubd()}
function ubd(){var b=$('bulkDeleteBtn');if(!b)return;var c=Object.keys(sel).length;if(c>0){b.style.display='';b.title='Hapus '+c+' terpilih';b.textContent='🗑 '+c}else b.style.display='none'}
D.selectMode=function(on){sm=on;var rows=($('dashboardTable')||{}).querySelectorAll('.dash-row');rows.forEach(function(r){r.classList.toggle('select-mode',on);var cb=r.querySelector('[data-a="check"]');if(cb)cb.style.display=on?'':'none';if(!on){cb.checked=false;delete sel[r.dataset.id]}});if(!on){sel={};ubd()}};
D.bulkDelete=function(){var ids=Object.keys(sel);if(!ids.length)return;var m=$('deleteMessage');if(m)m.textContent='Hapus '+ids.length+' link terpilih?';state.set('bulkIds',ids);C.showModal('deleteModal')};
D.updateCatList=function(){var e=$('dashCatList');if(e)e.innerHTML=state.get('cats').map(function(c){return'<option value="'+U.esc(c.name)+'">'}).join('')};
D.updateDrawerCatList=function(){var e=$('drawerCatInput');if(!e)return;var c=e.value;e.innerHTML=state.get('cats').map(function(x){return'<option value="'+U.esc(x.name)+'">'+U.esc(x.name)+'</option>'}).join('');e.value=c};
function rv(row){return{title:row.querySelector('[data-f="title"]').value,url:row.querySelector('[data-f="url"]').value,cat:row.querySelector('[data-f="cat"]').value}}
function rw(row){var id=row.dataset.id,l=state.get('links').find(function(x){return x.id===id});if(!l||!l._orig)return;var v=rv(row),ch=v.title!==l._orig.title||v.url!==l._orig.url||v.cat!==l._orig.cat;row.querySelector('[data-a="save"]').style.display=ch?'':'none'}
function sc(id){var row=$('dashboardTable').querySelector('[data-id="'+id+'"]');if(!row)return;var v=rv(row);try{new URL(v.url)}catch(e){C.toast('URL tidak valid','error');return}var btn=row.querySelector('[data-a="save"]');btn.disabled=true;btn.innerHTML='<span class="btn-spinner"></span>';db.saveRow(id,{title:v.title,url:v.url,categoryId:ci(v.cat)}).then(function(r){if(r.success){var l=state.get('links').find(function(x){return x.id===id});if(l){l.title=v.title;l.url=v.url;l.categoryId=ci(v.cat);l.updated=0;l._orig={title:v.title,url:v.url,cat:v.cat}}btn.disabled=false;btn.textContent='💾';btn.style.display='none';var ts2=row.querySelector('.dash-time span');if(ts2)ts2.textContent='Hari ini';C.toast('Link disimpan','success')}else{btn.disabled=false;btn.textContent='💾';C.toast('Gagal','error')}})}
function dc(id){var l=state.get('links').find(function(x){return x.id===id});if(!l)return;state.set('delId',id);state.set('bulkIds',null);var m=$('deleteMessage');if(m)m.textContent='Hapus "'+l.title+'"?';C.showModal('deleteModal')}
D.confirmDelete=function(){var b=state.get('bulkIds'),id=state.get('delId');C.hideModal('deleteModal');if(b&&b.length){D.dm(b)}else if(id){var l=state.get('links').find(function(x){return x.id===id});db.deleteRow(id).then(function(r){if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});sel={};ubd();D.render();if(l){C.toastUndo('"'+(l.title||'')+'" dihapus',function(){db.addRow({title:l.title,url:l.url,categoryId:l.categoryId}).then(function(){db.getData(true).then(function(d){state.set({cats:d.categories,links:d.links});D.render();C.toast('Dikembalikan','success')})})})}else C.toast('Link dihapus','success')})}else C.toast('Gagal','error')})}};
D.dm=function(ids){db.deleteMany(ids).then(function(r){if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});sel={};ubd();D.render();C.toast(ids.length+' link dihapus','success')})}else C.toast('Gagal','error')})};
D.openDrawer=function(link){$('drawerTitle').textContent=link?'Edit':'Tambah Link';$('drawerTitleInput').value=link?link.title:'';$('drawerUrlInput').value=link?link.url:'';$('drawerCatInput').value=link?cn(link.categoryId):(state.get('cats').length?state.get('cats')[0].name:'');$('slideDrawer').dataset.editId=link?link.id:'';C.showModal('slideDrawer');$('drawerTitleInput').focus()};
D.saveDrawer=function(){var id=$('slideDrawer').dataset.editId,t=$('drawerTitleInput').value.trim(),u=$('drawerUrlInput').value.trim(),c=$('drawerCatInput').value.trim();if(!t||!u){C.toast('Judul dan URL harus diisi','error');return}try{new URL(u)}catch(e){C.toast('URL tidak valid','error');return}var cid=ci(c)||(state.get('cats').length?state.get('cats')[0].id:''),btn=$('drawerSave');btn.disabled=true;btn.textContent='⏳';(id?db.saveRow(id,{title:t,url:u,categoryId:cid}):db.addRow({title:t,url:u,categoryId:cid})).then(function(r){btn.disabled=false;btn.textContent='Simpan';if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});D.render();C.hideModal('slideDrawer');C.toast('Link '+(id?'diperbarui':'ditambahkan'),'success')})}else C.toast('Gagal','error')})};
D.closeDrawer=function(){C.hideModal('slideDrawer')};
D.openSheet=function(){var b=$('catSheetBody');if(!b)return;var cats=state.get('cats').filter(function(c){return state.get('links').some(function(l){return l.categoryId===c.id})}),cur=state.get('tab');b.innerHTML=cats.map(function(c){var cnt=state.get('links').filter(function(l){return l.categoryId===c.id}).length;return'<button class="sheet-item '+(c.id===cur?'active':'')+'" data-id="'+c.id+'"><i data-feather="'+c.feather+'"></i><span>'+U.esc(c.name)+'</span><span class="sheet-count">'+cnt+'</span></button>'}).join('');b.querySelectorAll('.sheet-item').forEach(function(i){i.addEventListener('click',function(){var id=this.dataset.id,el=document.getElementById('dash-group-'+id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});D.closeSheet()})});if(typeof feather!=='undefined')feather.replace();C.showModal('catSheet')};
D.closeSheet=function(){C.hideModal('catSheet')};
D.openCatModal=function(){D.renderCatList();$('catNameInput').value='';C.showModal('catModal')};
D.renderCatList=function(){var e=$('catList');if(!e)return;e.innerHTML=state.get('cats').map(function(c){return'<div class="cat-item"><span>'+U.esc(c.name)+'</span><button class="cat-item-del" data-cat-id="'+c.id+'" title="Hapus">✕</button></div>'}).join('');e.querySelectorAll('.cat-item-del').forEach(function(b){b.addEventListener('click',function(){D.dc2(this.dataset.catId)})})};
D.addCategory=function(){var n=$('catNameInput').value.trim();if(!n){C.toast('Nama harus diisi','error');return}db.addCategory(n).then(function(r){if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});D.renderCatList();D.updateCatList();D.updateDrawerCatList();$('catNameInput').value='';C.toast('Kategori ditambahkan','success')})}else C.toast('Gagal','error')})};
D.dc2=function(id){var c=state.get('cats').find(function(x){return x.id===id});if(!c)return;var l=state.get('links').filter(function(x){return x.categoryId===id});if(l.length>0){C.toast('Masih ada '+l.length+' link di kategori ini','error');return}if(!confirm('Hapus "'+c.name+'"?'))return;db.deleteCategory(id).then(function(r){if(r.success){db.getData(true).then(function(data){state.set({cats:data.categories,links:data.links});D.renderCatList();D.updateCatList();D.updateDrawerCatList();D.render();C.toast('Kategori dihapus','success')})}else C.toast('Gagal','error')})};
D.renderNav=function(){var n=$('dashNav');if(!n)return;var cats=state.get('cats').filter(function(c){return state.get('links').some(function(l){return l.categoryId===c.id})});if(!cats.length){n.style.display='none';return}n.style.display='';n.innerHTML='<div class="dash-nav-title">Kategori</div>'+cats.map(function(c){var cnt=state.get('links').filter(function(l){return l.categoryId===c.id}).length;return'<a href="#" class="dash-nav-item" data-target="dash-group-'+c.id+'"><i data-feather="'+c.feather+'"></i><span>'+U.esc(c.name)+'</span><span class="dash-nav-count">'+cnt+'</span></a>'}).join('');n.querySelectorAll('.dash-nav-item').forEach(function(i){i.addEventListener('click',function(e){e.preventDefault();var el=document.getElementById(this.dataset.target);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})})});if(typeof feather!=='undefined')feather.replace();
var obs=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){var id=e.target.id.replace('dash-group-','');n.querySelectorAll('.dash-nav-item').forEach(function(i){i.classList.toggle('active',i.dataset.target==='dash-group-'+id)})}})},{rootMargin:'-70px 0px -65% 0px'});document.querySelectorAll('.dash-group').forEach(function(g){obs.observe(g)})};
D.renderCount=function(){var e=$('dashCount');if(e)e.textContent=state.get('links').length+' link'};
D.addRow=function(){D.openDrawer(null)};
D.exportCsv=function(){var ls=state.get('links');if(!ls.length){C.toast('Tidak ada link','error');return}var rows=[['id','title','url','category','updated','badge','sort']];ls.forEach(function(l){rows.push([l.id,l.title,l.url,cn(l.categoryId),l.updated,l.badge||'',typeof l.sort==='number'?l.sort:''])});var c=rows.map(function(r){return r.map(function(v){var s=String(v);return s.indexOf(',')!==-1||s.indexOf('"')!==-1||s.indexOf('\n')!==-1?'"'+s.replace(/"/g,'""')+'"':s}).join(',')}).join('\n'),b=new Blob([c],{type:'text/csv;charset=utf-8;'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='latch-links-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);C.toast('Export: '+ls.length+' link','success')};
D.importCsv=function(){var inp=document.createElement('input');inp.type='file';inp.accept='.csv';inp.addEventListener('change',function(){var f=inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){var t=e.target.result,lines=t.split('\n').filter(function(l){return l.trim()});if(lines.length<2){C.toast('CSV kosong','error');return}var h=lines[0].split(',').map(function(x){return x.trim().toLowerCase()}),ti=h.indexOf('title'),ui=h.indexOf('url'),ci=h.indexOf('category');if(ti===-1||ui===-1){C.toast('Butuh kolom title & url','error');return}var cats=state.get('cats'),added=0,chain=Promise.resolve();for(var i=1;i<lines.length;i++){(function(row){var vals=row.split(',').map(function(v){return v.trim().replace(/^"(.*)"$/,'$1').replace(/""/g,'"')}),title=vals[ti]||'',url=vals[ui]||'',cat=ci!==-1?(vals[ci]||''):'';if(!title||!url)return;chain=chain.then(function(){return db.addRow({title:title,url:url,categoryId:ci(cat)||(cats.length?cats[0].id:'')})}).then(function(r2){if(r2.success)added++})})(lines[i])}chain.then(function(){db.getData(true).then(function(d){state.set({cats:d.categories,links:d.links});D.render();C.toast('Import: '+added+' link','success')})})};r.readAsText(f)});inp.click()};
D.init=function(){D.render();D.startDashClock();D.bindEvents()};
D.startDashClock=function(){var e=$('dashClock');if(!e||e.dataset.clockStarted)return;e.dataset.clockStarted='1';function u(){var d=new Date(),days=['Min','Sen','Sel','Rab','Kam','Jum','Sab'],months=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];e.textContent=days[d.getDay()]+', '+d.getDate()+' '+months[d.getMonth()]+' '+d.getFullYear()+' · '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}u();setInterval(u,30000)};
D.bindEvents=function(){if($('slideDrawer'))$('slideDrawer').addEventListener('click',function(e){if(e.target===$('slideDrawer'))D.closeDrawer()});if($('drawerClose'))$('drawerClose').addEventListener('click',D.closeDrawer);if($('drawerSave'))$('drawerSave').addEventListener('click',D.saveDrawer);if($('drawerCancel'))$('drawerCancel').addEventListener('click',D.closeDrawer);if($('bulkDeleteBtn'))$('bulkDeleteBtn').addEventListener('click',D.bulkDelete);if($('dashSearchInput')){var ds=U.debounce(function(){D.renderTable();D.renderNav();D.renderCount()},300);$('dashSearchInput').addEventListener('input',ds)}if($('catManageBtn'))$('catManageBtn').addEventListener('click',D.openCatModal);if($('catAddBtn'))$('catAddBtn').addEventListener('click',D.addCategory);if($('catNameInput'))$('catNameInput').addEventListener('keydown',function(e){if(e.key==='Enter')D.addCategory()});if($('catClose'))$('catClose').addEventListener('click',function(){C.hideModal('catModal')});if($('catModal'))$('catModal').addEventListener('click',function(e){if(e.target===this)C.hideModal('catModal')});if($('shortcutModal'))$('shortcutModal').addEventListener('click',function(e){if(e.target===this)C.hideModal('shortcutModal')});if($('shortcutClose'))$('shortcutClose').addEventListener('click',function(){C.hideModal('shortcutModal')});if($('dashNavToggle'))$('dashNavToggle').addEventListener('click',D.openSheet);if($('catSheet'))$('catSheet').addEventListener('click',function(e){if(e.target===this)D.closeSheet()});if($('exportCsvBtn'))$('exportCsvBtn').addEventListener('click',D.exportCsv);if($('importCsvBtn'))$('importCsvBtn').addEventListener('click',D.importCsv);document.addEventListener('keydown',function(e){if(e.key==='?'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){var a=document.activeElement;if(a&&(a.tagName==='INPUT'||a.tagName==='TEXTAREA'))return;e.preventDefault();C.showModal('shortcutModal')}})};
window.LATCH=window.LATCH||{};window.LATCH.dashboard=D;
})();

/* theme */
(function(){'use strict';
var storage=window.LATCH.storage;var T={};
T.init=function(){var s=storage.get('latch-theme');if(s)document.documentElement.setAttribute('data-theme',s);else{document.documentElement.setAttribute('data-theme',window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light')}T.updateIcon()};
T.toggle=function(){var cur=document.documentElement.getAttribute('data-theme'),nxt=cur==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',nxt);storage.set('latch-theme',nxt);T.updateIcon()};
T.updateIcon=function(){if(typeof feather!=='undefined')feather.replace()};
window.LATCH=window.LATCH||{};window.LATCH.theme=T;
})();

/* app */
(function(){'use strict';
var state=window.LATCH.state;var db=window.LATCH.db;var C=window.LATCH.components;var U=window.LATCH.utils;var $=U.$id;var A={};
function init(){window.LATCH.layout.render().then(function(){var s=sessionStorage.getItem('latch-admin');if(s==='true')state.set({isAdmin:true,mode:'dashboard'});A.cacheDom();window.LATCH.theme.init();A.events();A.loadData()}).catch(function(err){console.error('[App]',err);var s=sessionStorage.getItem('latch-admin');if(s==='true')state.set({isAdmin:true,mode:'dashboard'});A.cacheDom();window.LATCH.theme.init();A.events();A.loadData()})}
A.cacheDom=function(){A.dom={view:$('viewContent'),dash:$('dashboardContent'),loginBtn:$('loginBtn'),loginModal:$('loginModal'),loginPin:$('loginPin'),loginErr:$('loginError'),loginSub:$('loginSubmit'),loginCan:$('loginCancel'),logout:$('logoutBtn'),addBtn:$('addRowBtn'),delModal:$('deleteModal'),delYes:$('deleteConfirm'),delNo:$('deleteCancel'),theme:$('themeToggle'),search:$('searchInput'),footer:$('footerArea')}};
A.events=function(){if(A.dom.theme)A.dom.theme.addEventListener('click',window.LATCH.theme.toggle);if(A.dom.search){var ds=U.debounce(function(){window.LATCH.view.onSearch(A.dom.search.value)},300);A.dom.search.addEventListener('input',ds)}document.addEventListener('keydown',A.onKey);if(A.dom.loginBtn)A.dom.loginBtn.addEventListener('click',A.showLogin);if(A.dom.loginSub)A.dom.loginSub.addEventListener('click',A.doLogin);if(A.dom.loginCan)A.dom.loginCan.addEventListener('click',A.hideLogin);if(A.dom.loginPin)A.dom.loginPin.addEventListener('keydown',function(e){if(e.key==='Enter')A.doLogin()});if(A.dom.loginModal)A.dom.loginModal.addEventListener('click',function(e){if(e.target===A.dom.loginModal)A.hideLogin()});if(A.dom.logout)A.dom.logout.addEventListener('click',A.doLogout);if(A.dom.addBtn)A.dom.addBtn.addEventListener('click',function(){window.LATCH.dashboard.addRow()});if(A.dom.delNo)A.dom.delNo.addEventListener('click',function(){C.hideModal('deleteModal')});if(A.dom.delYes)A.dom.delYes.addEventListener('click',function(){window.LATCH.dashboard.confirmDelete()});if(A.dom.delModal)A.dom.delModal.addEventListener('click',function(e){if(e.target===A.dom.delModal)C.hideModal('deleteModal')})};
A.onKey=function(e){if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();if(state.get('mode')==='dashboard'&&$('dashSearchInput'))$('dashSearchInput').focus();else if(A.dom.search)A.dom.search.focus()}if((e.ctrlKey||e.metaKey)&&e.key==='l'){e.preventDefault();if(state.get('mode')==='view'){var f=document.querySelector('.grid-container a');if(f)window.open(f.href,'_blank')}}if(e.key==='Escape'){if($('slideDrawer')&&$('slideDrawer').style.display==='flex'){window.LATCH.dashboard.closeDrawer();return}if(A.dom.loginModal&&A.dom.loginModal.style.display==='flex'){A.hideLogin();return}if(A.dom.delModal&&A.dom.delModal.style.display==='flex'){C.hideModal('deleteModal');return}if(state.get('mode')!=='dashboard'&&A.dom.search){A.dom.search.value='';window.LATCH.view.onSearch('');A.dom.search.blur()}}};
A.loadData=function(){C.showLoading();var lt=setTimeout(function(){C.hideLoading();C.toast('Gagal memuat data','error')},15000);db.getData().then(function(data){clearTimeout(lt);var cats=data.categories,all=data.links.slice(),vc=cats.map(function(c){return{id:c.id,name:c.name,feather:c.feather,links:data.links.filter(function(l){return l.categoryId===c.id})}});vc.unshift({id:'all',name:'Semua',feather:'grid',links:all});state.set({cats:cats,links:data.links,viewCats:vc});A.showMode();C.hideLoading()}).catch(function(err){clearTimeout(lt);C.hideLoading();C.toast('Gagal: '+(err.message||err),'error')})};
A.showMode=function(){var go=state.get('mode')==='dashboard'&&state.get('isAdmin'),out=go?A.dom.view:A.dom.dash,inn=go?A.dom.dash:A.dom.view;if(inn){if(go){A.initDashboard();if(A.dom.loginBtn)A.dom.loginBtn.style.display='none'}else{A.initView();if(A.dom.loginBtn)A.dom.loginBtn.style.display=''}if(out){out.classList.add('fade-out');inn.style.display='';inn.classList.remove('fade-in');void inn.offsetWidth;inn.classList.add('fade-in');setTimeout(function(){out.style.display='none';out.classList.remove('fade-out')},300)}else inn.style.display=''}};
A.initView=function(){window.LATCH.view.init()};
A.initDashboard=function(){window.LATCH.dashboard.init()};
A.showLogin=function(){if(A.dom.loginPin)A.dom.loginPin.value='';if(A.dom.loginErr)A.dom.loginErr.style.display='none';C.showModal('loginModal');if(A.dom.loginPin)A.dom.loginPin.focus()};
A.hideLogin=function(){C.hideModal('loginModal')};
A.doLogin=function(){var pin=A.dom.loginPin?A.dom.loginPin.value.trim():'';if(!pin){if(A.dom.loginErr){A.dom.loginErr.textContent='Masukkan PIN';A.dom.loginErr.style.display='block'}if(A.dom.loginPin)C.shakeElement(A.dom.loginPin);return}if(A.dom.loginSub){A.dom.loginSub.disabled=true;A.dom.loginSub.textContent='⏳'}db.verifyPin(pin).then(function(r){if(A.dom.loginSub){A.dom.loginSub.disabled=false;A.dom.loginSub.textContent='Masuk'}if(r.valid){A.hideLogin();state.set({isAdmin:true,mode:'dashboard'});A.showMode();C.toast('Selamat datang, Admin!','success')}else{if(A.dom.loginErr){A.dom.loginErr.textContent=r.error||'PIN salah';A.dom.loginErr.style.display='block'}if(A.dom.loginPin){A.dom.loginPin.focus();C.shakeElement(A.dom.loginPin)}}})};
A.doLogout=function(){sessionStorage.removeItem('latch-admin');state.set({isAdmin:false,mode:'view'});A.showMode();C.toast('Berhasil keluar','info')};
init();
})();
